services:
  mongo:
    image: mongo:7
    container_name: redalert-mongo
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: redalert-backend
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: redalert-frontend
    ports:
      - "4173:80"
    depends_on:
      - backend

volumes:
  mongo-data:
    
