name: Release

on:
  push:
    tags:
      - "v*" #check for tags starting with "v"

permissions:
  contents: write


jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and start services using docker compose
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 10

      - name: Bootstrap database
        run: docker compose exec -T backend python -m scripts.sync_mongo_data --drop-existing

      - name: Check backend API
        run: curl --fail http://127.0.0.1:8000/api/alerts/today

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
